### ISSUE TITLE
The plugin cannot import burp properly

### ISSUE THREAD

**Issue by Marco-zcl** [0x999-x/jsluicepp#1]
Hello author, I am glad to be able to use your plugin, but I encountered an issue during the import process. I installed jPython normally and placed it in the root directory of burp, and set the location of jython in burp. However, when I finished setting up the import plugin, there was an issue and I don't understand where the problem occurred

**Comment by Marco-zcl** [comment]
![Uploading 微信图片_20240211233154.png…]()

**Comment by Marco-zcl** [comment]
<img width="536" alt="微信图片_20240211233154" src="https://github.com/0x999-x/jsluicepp/assets/59686577/0c594f65-c65b-4631-b98d-312df6c26905">

**Comment by 0x999-x** [comment]
Hi,
Thank you for raising this issue,
would you mind pasting the full traceback error here?
I looked up part of the error that is visible in your screenshot and it appears to be caused by Jython not being able to handle non-ascii characters in the file path, could that be the case for you?
ref:
https://forum.portswigger.net/thread/error-while-trying-to-install-any-extensions-requiring-jython-44b5925e
https://forum.portswigger.net/thread/extension-f0efc7560be22682c4475eae4f

**Comment by Marco-zcl** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: (22, 'Invalid argument', 'D:\\??\\CTF2\\????\\Burp cj\\jsluicepp')

	at org.python.core.Py.OSError(Py.java:133)
	at org.python.modules.posix.PosixModule.absolutePath(PosixModule.java:1343)
	at org.python.modules.posix.PosixModule.chdir(PosixModule.java:300)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.pycode._pyx2.f$0(<string>:1)
	at org.python.pycode._pyx2.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1703)
	at org.python.core.Py.exec(Py.java:1747)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:268)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.c6p.<init>(Unknown Source)
	at burp.izp.a(Unknown Source)
	at burp.ah0.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by 0x999-x** [comment]
This appears to be the issue that I described above, it is happening because you have non-ascii characters in your file path and Jython fails to interpret them(notice the question marks in the path)
> Traceback (most recent call last): File "", line 1, in OSError: (22, 'Invalid argument', 'D:\??\CTF2\????\Burp cj\jsluicepp')

sadly there's little I can do about it as it's not an issue with the code rather with Jython, to fix it you can try one of the following -
1.Change the "Temporary files location" setting in burp to a custom location that doesn't include non-ascii characters in the path(as suggested [here](https://forum.portswigger.net/thread/error-while-trying-to-install-any-extensions-requiring-jython-44b5925e)

**Comment by 0x999-x** [comment]
This appears to be the issue that I described above, it is happening because you have non-ascii characters in your file path and Jython fails to interpret them(notice the question marks in the path)
> Traceback (most recent call last): File "", line 1, in OSError: (22, 'Invalid argument', 'D:\??\CTF2\????\Burp cj\jsluicepp')

sadly there's little I can do about it as it's not an issue with the code rather with Jython, to fix it you can try this to change the "Temporary files location" setting in burp to a custom location that doesn't include non-ascii characters in the path(as suggested [here](https://forum.portswigger.net/thread/error-while-trying-to-install-any-extensions-requiring-jython-44b5925e) or importing the extension from a path that doesn't include non-ascii characters

**Comment by Marco-zcl** [comment]
Thanks, this problem has been solved perfectly, and now you can use the plugin. I was so stupid.
